### ISSUE TITLE
Uncaught exception 

### ISSUE THREAD

**Issue by mark-cohen** [MagerValp/AutoDMG#137]
Build fails and throws exception (see below) using nested templates, OS only build works without issue. Templates open individually without issue. Replicated on 10.10.5, 10.11.1.

Here's the log:
[issue137.txt](https://github.com/MagerValp/AutoDMG/files/68430/issue137.txt)

**Comment by MagerValp** [comment]
Thank you, fixed the crash in fc2405029d45ab14bf0e028d70c3e313099a9bb7. Please try this build and see if it gives you a better error message: [AutoDMG-1.5.5b422](https://www.dropbox.com/s/3d8hxe2zgny754z/AutoDMG-1.5.5b422.dmg)

**Comment by mark-cohen** [comment]
(with Beta build) Now getting a "Failed to determine installed size" error.
![autodmg 1 5 5b422 error](https://cloud.githubusercontent.com/assets/16366976/11923381/7f2439ec-a757-11e5-9310-4161e3fc0259.png)

Here's the relevant log excerpt: 
2015-12-20 20:09:50 Error: Don't know how to calculate installed size for '/Volumes/Porta-Storage/Packages/AutoDMG templates/Internet-20151219.adtmpl'

**Comment by mark-cohen** [comment]
Here's the relevant output from attempting the same via the command line:

2015-12-20 20:30:05.957 AutoDMG[3079:50178] PyObjC: Converting exception to Objective-C:
Traceback (most recent call last):
  File "/Applications/AutoDMG.app/Contents/Resources/IEDWorkflow.py", line 516, in attachPackageDMG_
    self.continuePrepare()
  File "/Applications/AutoDMG.app/Contents/Resources/IEDWorkflow.py", line 556, in continuePrepare
    installedSize = IEDUtil.getInstalledPkgSize_(path)
  File "/Applications/AutoDMG.app/Contents/Resources/IEDUtil.py", line 122, in getInstalledPkgSize_
    pkgPath)
  File "/Applications/AutoDMG.app/Contents/Resources/IEDLog.py", line 317, in LogError
    LogMessage(IEDLogLevelError, NSString.stringWithFormat_(*args))
ValueError: depythonifying 'charptr', got 'objc.pyobjc_unicode'
2015-12-20 20:30:05.960 AutoDMG[3079:50178] AutoDMG died with an uncaught exception depythonifying 'charptr', got 'objc.pyobjc_unicode': Traceback (most recent call last):
  File "/Applications/AutoDMG.app/Contents/Resources/main.py", line 199, in main
    status = cli_main(decoded_argv)
  File "/Applications/AutoDMG.app/Contents/Resources/main.py", line 169, in cli_main
    return args.func(args)
  File "/Applications/AutoDMG.app/Contents/Resources/IEDCLIController.py", line 223, in cmdBuild_
    self.waitBusy()
  File "/Applications/AutoDMG.app/Contents/Resources/IEDCLIController.py", line 65, in waitBusy
    if not runLoop.runMode_beforeDate_(NSDefaultRunLoopMode, nextfire):
  File "/Applications/AutoDMG.app/Contents/Resources/IEDWorkflow.py", line 516, in attachPackageDMG_
    self.continuePrepare()
  File "/Applications/AutoDMG.app/Contents/Resources/IEDWorkflow.py", line 556, in continuePrepare
    installedSize = IEDUtil.getInstalledPkgSize_(path)
  File "/Applications/AutoDMG.app/Contents/Resources/IEDUtil.py", line 122, in getInstalledPkgSize_
    pkgPath)
  File "/Applications/AutoDMG.app/Contents/Resources/IEDLog.py", line 317, in LogError
    LogMessage(IEDLogLevelError, NSString.stringWithFormat_(*args))
ValueError: depythonifying 'charptr', got 'objc.pyobjc_unicode'
2015-12-20 20:30:05.960 AutoDMG[3079:50178] Closing stdout/stderr

**Comment by MagerValp** [comment]
It looks like you added `3S-20151219.adtmpl` to `AdditionalPackages` instead of `IncludeTemplates`? I added additional verification to [AutoDMG-1.5.5b424](https://www.dropbox.com/s/sfvclt5oi8vqb8j/AutoDMG-1.5.5b424.dmg) which should give a proper error message.

**Comment by mark-cohen** [comment]
Indeed I did. 1.5.5b424's error message is indeed an improvement (vs no message):
![screen shot 2015-12-21 at 11 20 26 am](https://cloud.githubusercontent.com/assets/16366976/11939169/1574a490-a7d5-11e5-8a03-ce1811f4d441.png)


Thanks.

**Comment by MagerValp** [comment]
Good, closing.
