### ISSUE TITLE
Doesn't handle detaching dmgs that don't want to go away very well

### ISSUE THREAD

**Issue by nmcspadden** [MagerValp/AutoDMG#171]
I can pretty reliably reproduce this by killing AutoDMG partway through a build, and leaving all the open disk images mounted. If /usr/bin/installer is in the process of trying to install something (and therefore won't let one of the disk images be unmounted, and is otherwise using the resource), this issue happens 100% of the time (for me, at least).

The disks don't eject and AutoDMG instead dies:
```
Traceback (most recent call last):
  File "/Applications/AutoDMG.app/Contents/Resources/IEDWorkflow.py", line 89, in handleDetachResult_
    self.delegate.detachFailed_details_(result[u"dmg-path"], result[u"error-message"])
AttributeError: 'IEDCLIController' object has no attribute 'detachFailed_details_'
2017-01-11 07:41:16.977 AutoDMG[44889:447804] AutoDMG died with an uncaught exception 'IEDCLIController' object has no attribute 'detachFailed_details_': Traceback (most recen
t call last):
  File "/Applications/AutoDMG.app/Contents/Resources/main.py", line 215, in main
    status = cli_main(decoded_argv)
  File "/Applications/AutoDMG.app/Contents/Resources/main.py", line 169, in cli_main
    return args.func(args)
  File "/Applications/AutoDMG.app/Contents/Resources/IEDCLIController.py", line 227, in cmdBuild_
    self.waitBusy()
  File "/Applications/AutoDMG.app/Contents/Resources/IEDCLIController.py", line 62, in waitBusy
    nextfire = runLoop.limitDateForMode_(NSDefaultRunLoopMode)
  File "/Applications/AutoDMG.app/Contents/Resources/IEDWorkflow.py", line 89, in handleDetachResult_
    self.delegate.detachFailed_details_(result[u"dmg-path"], result[u"error-message"])
AttributeError: 'IEDCLIController' object has no attribute 'detachFailed_details_'
```

**Comment by MagerValp** [comment]
Please try [AutoDMG-1.7.4b509](https://www.dropbox.com/s/kfx67gfmfnbxm89/AutoDMG-1.7.4b509.dmg).

**Comment by nmcspadden** [comment]
The latest version seems to resolve it, thanks!
