### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by SilverCha0s** [MagerValp/AutoDMG#179]
Not sure if this is an issue for everyone, but AutoDMG crashes everytime for me with the following error

[import_main_py_crash.txt](https://github.com/MagerValp/AutoDMG/files/957408/import_main_py_crash.txt)

**Comment by MagerValp** [comment]
I've been looking at the crash report and there are very few clues as to what's wrong. Could you try running it in the Terminal instead? There should be an error message printed that could give us a better idea. Start it with: `/Applications/AutoDMG.app/Contents/MacOS/AutoDMG`.

**Comment by nbalonso** [comment]
This started happening to me recently

```bash
$ /Applications/AutoDMG.app/Contents/MacOS/AutoDMG
Traceback (most recent call last):
  File "/Applications/AutoDMG.app/Contents/Resources/main.py", line 15, in <module>
    import objc
ImportError: No module named objc
2017-05-28 09:19:47.264 AutoDMG[6885:261359] UncaughtExceptionHandler:
2017-05-28 09:19:47.264 AutoDMG[6885:261359] Import of main.py failed
2017-05-28 09:19:47.264 AutoDMG[6885:261359] User info: (null)
2017-05-28 09:19:47.264 AutoDMG[6885:261359] Strack trace: (null)
2017-05-28 09:19:47.264 AutoDMG[6885:261359] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Import of main.py failed'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fffcceab57b __exceptionPreprocess + 171
        1   libobjc.A.dylib                     0x00007fffe20ef1da objc_exception_throw + 48
        2   CoreFoundation                      0x00007fffccf28c55 +[NSException raise:format:] + 197
        3   AutoDMG                             0x0000000104aafa2c AutoDMG + 10796
        4   libdyld.dylib                       0x00007fffe29d0235 start + 1
        5   ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
$ which python
/usr/local/bin/python
$ /usr/local/bin/python --version
Python 2.7.13
$ brew unlink python
Unlinking /usr/local/Cellar/python/2.7.13... 39 symlinks removed
$ which python
/usr/bin/python
$ /usr/bin/python --version
Python 2.7.10
$ /Applications/AutoDMG.app/Contents/MacOS/AutoDMG
Traceback (most recent call last):
  File "/Applications/AutoDMG.app/Contents/Resources/main.py", line 15, in <module>
    import objc
ImportError: No module named objc
2017-05-28 09:22:00.047 AutoDMG[7230:263580] UncaughtExceptionHandler:
2017-05-28 09:22:00.047 AutoDMG[7230:263580] Import of main.py failed
2017-05-28 09:22:00.047 AutoDMG[7230:263580] User info: (null)
2017-05-28 09:22:00.047 AutoDMG[7230:263580] Strack trace: (null)
2017-05-28 09:22:00.047 AutoDMG[7230:263580] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Import of main.py failed'
*** First throw call stack:
(
        0   CoreFoundation                      0x00007fffcceab57b __exceptionPreprocess + 171
        1   libobjc.A.dylib                     0x00007fffe20ef1da objc_exception_throw + 48
        2   CoreFoundation                      0x00007fffccf28c55 +[NSException raise:format:] + 197
        3   AutoDMG                             0x0000000109e49a2c AutoDMG + 10796
        4   libdyld.dylib                       0x00007fffe29d0235 start + 1
        5   ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
$
```
🤔

**Comment by MagerValp** [comment]
@nbalonso That's the error you get if you have a 3rd party Python install without PyObjC.

**Comment by timsutton** [comment]
@MagerValp As discussed this morning in Slack, I got a startup crash before I realized that it's because I had previously `sudo pip install`ed PyObjC on this system for something else. Here's the startup crash:


```
$ /Applications/AutoDMG.app/Contents/MacOS/AutoDMG 
Traceback (most recent call last):
  File "/Applications/AutoDMG.app/Contents/Resources/main.py", line 22, in <module>
    from IEDLog import LogDebug, LogInfo, LogNotice, LogWarning, LogError, LogMessage
  File "/Applications/AutoDMG.app/Contents/Resources/IEDLog.py", line 16, in <module>
    from IEDLogLine import *
  File "/Applications/AutoDMG.app/Contents/Resources/IEDLogLine.py", line 15, in <module>
    class IEDLogLine(NSObject):
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector setLevel of IEDLogLine at 0x116000a58>
2017-06-06 09:12:22.150 AutoDMG[637:8728] UncaughtExceptionHandler:
2017-06-06 09:12:22.150 AutoDMG[637:8728] Import of main.py failed
2017-06-06 09:12:22.150 AutoDMG[637:8728] User info: (null)
2017-06-06 09:12:22.150 AutoDMG[637:8728] Strack trace: (null)
2017-06-06 09:12:22.150 AutoDMG[637:8728] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Import of main.py failed'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109f0328b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000109130d06 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000109f9dfad +[NSException raise:format:] + 205
	3   AutoDMG                             0x00000001088d3a43 AutoDMG + 10819
	4   libdyld.dylib                       0x000000010b2dd515 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

And here's the full crash (note the PyObjC Cocoa stuff installed in `/L/Python/2.7/site-packages`:

[autodmg_crash.txt](https://github.com/MagerValp/AutoDMG/files/1055124/autodmg_crash.txt)

**Comment by MagerValp** [comment]
Thank you. Closing this issue as the fix basically involves shipping my own Python framework (which I'm considering).
