### ISSUE TITLE
Cannot build on Mac OS 10.15 Catalina 19A471t

### ISSUE THREAD

**Issue by maaboo** [MagerValp/AutoDMG#232]
## Description of issue

Cannot build on Mac OS 10.15 Catalina

## Expected behavior

Build starts

## Actual behavior

Build fails with error message:

The save operation failed
The save operation failed to connect to the open and save panel service

## Steps to reproduce

1. Update Mac OS to 10.15 19A471t
2. Start to build with app

## Log file

Log also cannot be saved

<img width="2560" alt="autodmg-1 9-catalina-beta-issue" src="https://user-images.githubusercontent.com/912261/58869892-c730f880-86c7-11e9-86a0-84156d694dd2.png">
<img width="1068" alt="autodmg-1 9-catalina-beta-issue-log" src="https://user-images.githubusercontent.com/912261/58869894-c7c98f00-86c7-11e9-9e47-638d794f2d8f.png">

**Comment by MagerValp** [comment]
Crash log:

```[NSSavePanel advanceToRunPhaseIfNeededLayerCentric]_block_invoke : Could not advance an Open/Save panel to run phase due to error: Error Domain=com.apple.ViewBridge Code=16 "(null)" UserInfo={com.apple.ViewBridge.error.hint=advance to run phase, com.apple.ViewBridge.error.description=NSViewBridgeServiceInvalidError}
[NSSavePanel advanceToRunPhaseIfNeededLayerCentric] : an exception occurred during attempt to advance an Open/Save panel to run phase!
[NSSavePanel runModal] caught non-fatal NSObjectNotAvailableException 'The operation couldn’t be completed. (com.apple.ViewBridge error 16.)' with user dictionary {
    error = "Error Domain=com.apple.ViewBridge Code=16 \"(null)\" UserInfo={com.apple.ViewBridge.error.hint=advance to run phase, com.apple.ViewBridge.error.description=NSViewBridgeServiceInvalidError}";
} and backtrace (
	0   CoreFoundation                      0x00007fff31f06c63 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff673cf06b objc_exception_throw + 48
	2   AppKit                              0x00007fff2fbe68bf -[NSSavePanel advanceToRunPhaseIfNeededLayerCentric] + 763
	3   AppKit                              0x00007fff2fbe7045 -[NSSavePanel runModal] + 106
	4   libffi.dylib                        0x00007fff66360915 ffi_call_unix64 + 85
	5   ???                                 0x000060000001b4f0 0x0 + 105553116378352
)
```

**Comment by rickheil** [comment]
Log for CLI build on 10.15 with a normal user.

`Onepaths-MacBook-Pro:Downloads onepath$ /Volumes/AutoDMG-1.9/AutoDMG.app/Contents/MacOS/AutoDMG -v build --output ~/Desktop/test.apfs --installer /Volumes/Install\ macOS\ 10.15\ Beta/Install\ macOS\ 10.15\ Beta.app -n "testing 123" -s 100
Onepaths-MacBook-Pro:Downloads onepath$ /Volumes/AutoDMG-1.9/AutoDMG.app/Contents/MacOS/AutoDMG -v build /Volumes/Install\ macOS\ 10.15\ Beta/Install\ macOS\ 10.15\ Beta.app --output ~/Desktop/test.apfs -n "Testing" -s 100
AutoDMG v1.9 build 578
Mac OS X 10.15 19A471t
CPython 2.7.10 (GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.21.8))
PyObjC 2.5.1
Setting source path to '/Volumes/Install macOS 10.15 Beta/Install macOS 10.15 Beta.app'
Setting output path to '/Users/onepath/Desktop/test.apfs'
Setting volume name to 'Testing'
Setting volume size to '100'
Installer: /Volumes/Install macOS 10.15 Beta/Install macOS 10.15 Beta.app
Examining source…
Found source: Mac OS X 10.15 19A471t
Accepted source /Volumes/Install macOS 10.15 Beta/Install macOS 10.15 Beta.app: Mac OS X 10.15 19A471t
Found installer: Mac OS X 10.15 19A471t
Output Path: /Users/onepath/Desktop/test.apfs
Volume Name: Testing
Password for onepath: 
Unrecognized filesystem setting '(null)'
Starting build
Using installer: Mac OS X 10.15 19A471t
Using output path: /Users/onepath/Desktop/test.apfs
TMPDIR is set to: /var/folders/nr/_vpp8ds12y9dmzkmxw378znm0000gn/T/
Task taskPrepare with 1 phases:
    Phase 'Preparing' with weight 34.0
Task taskInstall with 4 phases:
    Phase 'Starting install' with weight 21.0
    Phase 'Creating disk image' with weight 21.0
    Phase 'Installing OS' with weight 4096.0
    Phase 'Converting disk image' with weight 313.0
Task taskFinalize with 4 phases:
    Phase 'Scanning disk image' with weight 2.0
    Phase 'Scanning disk image' with weight 1.0
    Phase 'Scanning disk image' with weight 150.0
    Phase 'Scanning disk image' with weight 17.0
Task taskFinish with 1 phases:
    Phase 'Finishing' with weight 1.0
Starting task Prepare with 1 phases
Starting phase: Preparing
phase: Preparing
progress: 0.0%
1 packages to install:
    /Volumes/Install macOS 10.15 Beta/Install macOS 10.15 Beta.app/Contents/SharedSupport/InstallInfo.plist requires 16.2 GB
Workflow requires a 16.2 GB disk image
Using a 100 GB disk image
Starting task Install with 4 phases
Phase Preparing with weight 35651584 finished after 0.006 seconds
Starting phase: Starting install
phase: Starting install
progress: 0.7%
Install task running
Launching install with arguments:
    '/Volumes/AutoDMG-1.9/AutoDMG.app/Contents/Resources/progresswatcher.py'
    '--cd'
    '/Volumes/AutoDMG-1.9/AutoDMG.app/Contents/Resources'
    '--socket'
    '/tmp/se.gu.it.IEDSocketListener.64ecb4af0adb8c39'
    'installesdtodmg'
    '--user'
    '501'
    '--group'
    '20'
    '--fstype'
    'apfs'
    '--output'
    '/Users/onepath/Desktop/test.apfs'
    '--volume-name'
    'Testing'
    '--size'
    '100'
    '--template'
    '/var/folders/nr/_vpp8ds12y9dmzkmxw378znm0000gn/T/tmpWM6ctb/AutoDMG-20190604.adtmpl'
    '/Volumes/Install macOS 10.15 Beta/Install macOS 10.15 Beta.app/Contents/SharedSupport/InstallInfo.plist'
Install task launched with sudo
Install task finished with exit status 70
Workflow failed: Build failed (Install task failed with status 70)
Build failed: Build failed
    Install task failed with status 70
`

**Comment by rickheil** [comment]
When running with sudo and passing -r:

```Onepaths-MacBook-Pro:Downloads onepath$ sudo /Volumes/AutoDMG-1.9/AutoDMG.app/Contents/MacOS/AutoDMG -v -r build /Volumes/Install\ macOS\ 10.15\ Beta/Install\ macOS\ 10.15\ Beta.app --output ~/Desktop/test.apfs -n "Testing" -s 100
2019-06-04 17:28:32.126 AutoDMG[12957:144790] TMPDIR is not set
Running as root, using /var/root/Library/Application Support/AutoDMG
AutoDMG v1.9 build 578
Mac OS X 10.15 19A471t
CPython 2.7.10 (GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.21.8))
PyObjC 2.5.1
Setting source path to '/Volumes/Install macOS 10.15 Beta/Install macOS 10.15 Beta.app'
Setting output path to '/Users/onepath/Desktop/test.apfs'
Setting volume name to 'Testing'
Setting volume size to '100'
Installer: /Volumes/Install macOS 10.15 Beta/Install macOS 10.15 Beta.app
Examining source…
Found source: Mac OS X 10.15 19A471t
Accepted source /Volumes/Install macOS 10.15 Beta/Install macOS 10.15 Beta.app: Mac OS X 10.15 19A471t
Found installer: Mac OS X 10.15 19A471t
Output Path: /Users/onepath/Desktop/test.apfs
Volume Name: Testing
Unrecognized filesystem setting '(null)'
Starting build
Using installer: Mac OS X 10.15 19A471t
Using output path: /Users/onepath/Desktop/test.apfs
TMPDIR is set to: (null)
Task taskPrepare with 1 phases:
    Phase 'Preparing' with weight 34.0
Task taskInstall with 4 phases:
    Phase 'Starting install' with weight 21.0
    Phase 'Creating disk image' with weight 21.0
    Phase 'Installing OS' with weight 4096.0
    Phase 'Converting disk image' with weight 313.0
Task taskFinalize with 4 phases:
    Phase 'Scanning disk image' with weight 2.0
    Phase 'Scanning disk image' with weight 1.0
    Phase 'Scanning disk image' with weight 150.0
    Phase 'Scanning disk image' with weight 17.0
Task taskFinish with 1 phases:
    Phase 'Finishing' with weight 1.0
Starting task Prepare with 1 phases
Starting phase: Preparing
phase: Preparing
progress: 0.0%
1 packages to install:
    /Volumes/Install macOS 10.15 Beta/Install macOS 10.15 Beta.app/Contents/SharedSupport/InstallInfo.plist requires 16.2 GB
Workflow requires a 16.2 GB disk image
Using a 100 GB disk image
Starting task Install with 4 phases
Phase Preparing with weight 35651584 finished after 0.007 seconds
Starting phase: Starting install
phase: Starting install
progress: 0.7%
Install task running
Launching install with arguments:
    '/Volumes/AutoDMG-1.9/AutoDMG.app/Contents/Resources/progresswatcher.py'
    '--cd'
    '/Volumes/AutoDMG-1.9/AutoDMG.app/Contents/Resources'
    '--socket'
    '/tmp/se.gu.it.IEDSocketListener.259de147ae1af35d'
    'installesdtodmg'
    '--user'
    '0'
    '--group'
    '0'
    '--fstype'
    'apfs'
    '--output'
    '/Users/onepath/Desktop/test.apfs'
    '--volume-name'
    'Testing'
    '--size'
    '100'
    '--template'
    '/tmp/tmpJcpvJy/AutoDMG-20190604.adtmpl'
    '/Volumes/Install macOS 10.15 Beta/Install macOS 10.15 Beta.app/Contents/SharedSupport/InstallInfo.plist'
Install task launched
2019-06-04 17:28:33.160 Python[12973:144959] progresswatcher launching
2019-06-04 17:28:33.160 Python[12973:144959] progresswatcher arguments: (
    "/Volumes/AutoDMG-1.9/AutoDMG.app/Contents/Resources/progresswatcher.py",
    "--cd",
    "/Volumes/AutoDMG-1.9/AutoDMG.app/Contents/Resources",
    "--socket",
    "/tmp/se.gu.it.IEDSocketListener.259de147ae1af35d",
    installesdtodmg,
    "--user",
    0,
    "--group",
    0,
    "--fstype",
    apfs,
    "--output",
    "/Users/onepath/Desktop/test.apfs",
    "--volume-name",
    Testing,
    "--size",
    100,
    "--template",
    "/tmp/tmpJcpvJy/AutoDMG-20190604.adtmpl",
    "/Volumes/Install macOS 10.15 Beta/Install macOS 10.15 Beta.app/Contents/SharedSupport/InstallInfo.plist"
)
2019-06-04 17:28:33.160 Python[12973:144959] progresswatcher uid: 0, euid: 0
2019-06-04 17:28:33.164 Python[12973:144959] progresswatcher language: en
2019-06-04 17:28:33.167 Python[12973:144959] progresswatcher uid: 0, euid: 0
2019-06-04 17:28:33.170 Python[12973:144959] progresswatcher died with an uncaught exception: Traceback (most recent call last):
  File "/Volumes/AutoDMG-1.9/AutoDMG.app/Contents/Resources/progresswatcher.py", line 363, in main
    args.func(args)
  File "/Volumes/AutoDMG-1.9/AutoDMG.app/Contents/Resources/progresswatcher.py", line 324, in installesdtodmg
    run(pwargs, args.socket, "ied")
  File "/Volumes/AutoDMG-1.9/AutoDMG.app/Contents/Resources/progresswatcher.py", line 300, in run
    pw.watchTask_socket_mode_(args, sockPath, mode)
  File "/Volumes/AutoDMG-1.9/AutoDMG.app/Contents/Resources/progresswatcher.py", line 76, in watchTask_socket_mode_
    task.launch()
ValueError: NSInvalidArgumentException - *** -scheduleInRunLoop:forMode: cannot be sent to an abstract object of class NSMachPort: Create a concrete instance!
2019-06-04 17:28:33.170 Python[12973:144959] PyObjC: Exception during dealloc of proxy: *** -removeFromRunLoop:forMode: cannot be sent to an abstract object of class NSMachPort: Create a concrete instance!
Install task finished with exit status 70
Workflow failed: Build failed (Install task failed with status 70)
Build failed: Build failed
    Install task failed with status 70
```

**Comment by chilcote** [comment]
More logs

```
default	14:40:23.321445-0700	runningboardd	Acquiring assertion targeting executable<AutoDMG(502)> from originator [daemon<com.apple.coreservices.launchservicesd>:120] with description <RBSAssertionDescriptor; frontmost:26245; ID: 204-120-2175; target: 26245> attributes = {
    <RBSDomainAttribute: 0x7fa43d734370; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
default	14:40:23.321567-0700	runningboardd	Assertion 204-120-2175 (target:executable<AutoDMG(502)>) will be created as active
default	14:40:23.322179-0700	runningboardd	Finished acquiring assertion 204-120-2175 (target:executable<AutoDMG(502)>)
default	14:40:23.322319-0700	runningboardd	[executable<AutoDMG(502)>:26245] Ignoring jetsam update because this process is not memory-managed
default	14:40:23.322935-0700	runningboardd	[executable<AutoDMG(502)>:26245] Set darwin role to: UserInteractiveFocal
default	14:40:23.323250-0700	runningboardd	[executable<AutoDMG(502)>:26245] Ignoring GPU update because this process is not GPU managed
default	14:40:23.544559-0700	AutoDMG	-[NSSavePanel advanceToRunPhaseIfNeededLayerCentric]_block_invoke : Could not advance an Open/Save panel to run phase due to error: Error Domain=com.apple.ViewBridge Code=16 "(null)" UserInfo={com.apple.ViewBridge.error.hint=advance to run phase, com.apple.ViewBridge.error.description=NSViewBridgeServiceInvalidError}
default	14:40:23.544672-0700	AutoDMG	-[NSSavePanel advanceToRunPhaseIfNeededLayerCentric] : an exception occurred during attempt to advance an Open/Save panel to run phase!
default	14:40:23.544954-0700	AutoDMG	-[NSSavePanel runModal] caught non-fatal NSObjectNotAvailableException 'The operation couldn’t be completed. (com.apple.ViewBridge error 16.)' with user dictionary {
    error = "Error Domain=com.apple.ViewBridge Code=16 \"(null)\" UserInfo={com.apple.ViewBridge.error.hint=advance to run phase, com.apple.ViewBridge.error.description=NSViewBridgeServiceInvalidError}";
} and backtrace (
	0   CoreFoundation                      0x00007fff30042c63 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6550b06b objc_exception_throw + 48
	2   AppKit                              0x00007fff2dd228bf -[NSSavePanel advanceToRunPhaseIfNeededLayerCentric] + 763
	3   AppKit                              0x00007fff2dd23045 -[NSSavePanel runModal] + 106
	4   libffi.dylib                        0x00007fff6449c915 ffi_call_unix64 + 85
	5   ???                                 0x0000600000721d60 0x0 + 105553123745120
)
default	14:40:27.256411-0700	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: AutoDMG__WSWindow__WSWindowDrag **** frame data ****
default	14:40:27.256443-0700	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: AutoDMG__WSWindow__WSWindowDrag __frames/s (IntervalRate)__ 45.9
default	14:40:27.256469-0700	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: AutoDMG__WSWindow__WSWindowDrag __frames/s (IntervalRateIgnoringDelay)__ 48.3
default	14:40:27.256509-0700	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: AutoDMG__WSWindow__WSWindowDrag __ms (OperationDuration)__ 479.3
default	14:40:27.256532-0700	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: AutoDMG__WSWindow__WSWindowDrag __ms/frame (AverageDuration)__ 16.4
default	14:40:27.256586-0700	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: AutoDMG__WSWindow__WSWindowDrag __ms/frame (StandardDeviation)__ 1.1
default	14:40:27.256623-0700	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: AutoDMG__WSWindow__WSWindowDrag __(NormalizedStandardDeviation)__ 0.1
default	14:40:27.256647-0700	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: AutoDMG__WSWindow__WSWindowDrag __ms (DelayFromOperationStart)__ 23.4
default	14:40:27.256675-0700	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: AutoDMG__WSWindow__WSWindowDrag __frames (IntervalCount)__ 22.0
default	14:40:27.256717-0700	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: AutoDMG__WSWindow__WSWindowDrag **** Slow WS Update data ****
default	14:40:27.256743-0700	com.apple.PerformanceAnalysis.animationperfd	__PerfLogging__: AutoDMG__WSWindow__WSWindowDrag __updates (Slow WS Update count)__ 0
default	14:40:35.553392-0700	runningboardd	Invalidating assertion 204-120-2175 (target:executable<AutoDMG(502)>) from originator 120
default	14:40:35.658519-0700	runningboardd	[executable<AutoDMG(502)>:26245] Ignoring jetsam update because this process is not memory-managed
default	14:40:35.658557-0700	runningboardd	[executable<AutoDMG(502)>:26245] Set darwin role to: UserInteractiveNonFocal
default	14:40:35.658584-0700	runningboardd	[executable<AutoDMG(502)>:26245] Ignoring GPU update because this process is not GPU managed
```

**Comment by MagerValp** [comment]
@rickheil Alright, that looks like a different issue in your CLI run.
